### ISSUE TITLE
Question: pipe stream to POST request

### ISSUE THREAD

**Issue by mulyoved** [googleapis/retry-request#3]
Have this code which work fine with request, what will be the correct way to call it in retry-request?

```
var pipe = fs
  .createReadStream(fileName)
  .pipe(
  request({ url: url, method: 'POST'}));

pipe
  .on('error', function(err) {
    console.error(err);
  })
  .on('response', function (answer) {
  })
  .on('complete', function (answer) {
  })
  .on('end', function(answer) {
  });
```

**Comment by stephenplusplus** [comment]
It should look like:

```diff
var pipe = fs
  .createReadStream(fileName)
  .pipe(
-  request({ url: url, method: 'POST'}));
+  retryRequest({ url: url, method: 'POST'}));

pipe
  .on('error', function(err) {
    console.error(err);
  })
  .on('response', function (answer) {
  })
  .on('complete', function (answer) {
  })
  .on('end', function(answer) {
  });
```

Can you let me know if that works?

**Comment by mulyoved** [comment]
No this does not work, all look OK but result seem to be empty stream.

**Comment by stephenplusplus** [comment]
Sorry, I don't know how I missed the `POST` part of this, since it was all over your question.

Using `retryRequest` with post requests is not currently supported, as it's quite a difficult task to implement. Conditionally rewinding & re-piping a stream already in the hands of a user is not something I've yet figured out how to do, if it is even possible at all. PRs welcome if you know the trick!

**Comment by stephenplusplus** [comment]
Left a note in the readme that points here.

**Comment by mulyoved** [comment]
I can see why stream POST is an issue, I ended up add the retry logic in an upper level.

**Comment by ruffle1986** [comment]
Sorry, it's a bit irrelevant. @stephenplusplus, how did you achieve the red and green lines to show the changes in your comment?

**Comment by stephenplusplus** [comment]
No problem @ruffle1986. I thought it was pretty cool the first time I saw it, too.

```
```diff
var pipe = fs
  .createReadStream(fileName)
  .pipe(
-  request({ url: url, method: 'POST'}));
+  retryRequest({ url: url, method: 'POST'}));
```
:arrow_double_down: 
```diff
var pipe = fs
  .createReadStream(fileName)
  .pipe(
-  request({ url: url, method: 'POST'}));
+  retryRequest({ url: url, method: 'POST'}));
```

**Comment by surya1024** [comment]
I have similar issue even with get 
Using pump returns a empty response
`  pump(req, retryRequest({...options, url: url}), res, (err) => console.log(err));
`
Using pipe gives a "write after end" error
`        req.pipe(request({url: "http://localhost:8081/digital-image-service/v1/image?chpImageFileId=12355", ...options}))
           .on('error', (req, res, next) => console.log("error"))
           .pipe(res);`

**Comment by stephenplusplus** [comment]
@surya1024 thank you for reporting. Would you mind opening a new issue for that?
