### ISSUE TITLE
shouldRetryFn never get used on errors

### ISSUE THREAD

**Issue by daneshka** [googleapis/retry-request#30]
My Issue:
I'm using this library indirectly via [google bigtable](https://github.com/googleapis/nodejs-bigtable/)
My issue is when I set a timeout on GaxOptions, it will get back with the timeout error after all the retries.
When I checked the issue I saw here in this part of the code there are 2 problems.
https://github.com/stephenplusplus/retry-request/blob/master/index.js#L175-L196

1. when there is an error, we start retrying before `shouldRetryFn`
2. shouldRetryFn doesn't include grpc timeout (or any other grpc error).

**Comment by tmatsuo** [comment]
@daneshka Sorry for the late reply, but can you

1. use a permalink (link with a commit hash) for referring some code
2. provide a reproducible code
3. tell us what do you expect instead

?
Thanks

**Comment by daneshka** [comment]
Hi @tmatsuo 
this ticket is too old.
I think you could close it.

**Comment by bcoe** [comment]
@daneshka 👍 sorry for this, please let us know if you bump into any issues in the future. This repo is now falling under our SLOs.
