### ISSUE TITLE
end event not being properly propagated when no data available.

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/retry-request#31]
`end` event not being properly emitting when no data available.

Here is `bigtable` issue [612](https://github.com/googleapis/nodejs-bigtable/issues/612) and [555](https://github.com/googleapis/nodejs-bigtable/issues/555)

**Comment by stephenplusplus** [comment]
I did some research over on the original Bigtable issue: https://github.com/googleapis/nodejs-bigtable/issues/612#issuecomment-589133501. Let's call this issue blocked for now, as I'm not sure what (if anything), we'll need to do from this library. I've closed the related PR as well.
