### ISSUE TITLE
Missing dependency `request` causes an error when using Google Cloud's Vision API

### ISSUE THREAD

**Issue by tferrerm** [googleapis/retry-request#39]
When using `webpack` with `npm` to bundle a project which uses [@google-cloud/vision](https://www.npmjs.com/package/@google-cloud/vision) the following error occurs:
```
WARNING in ./node_modules/retry-request/index.js 74:21-39
Module not found: Error: Can't resolve 'request' in '/home/user/project/node_modules/retry-request'
 @ ./node_modules/@google-cloud/vision/node_modules/google-gax/build/src/streamingCalls/streaming.js 22:21-45
 @ ./node_modules/@google-cloud/vision/node_modules/google-gax/build/src/index.js 64:18-55
 @ ./node_modules/@google-cloud/vision/build/src/helpers.js 24:12-33
 @ ./node_modules/@google-cloud/vision/build/src/index.js 31:16-36
 @ ./src/image-service/handler/lambdaGcloudWorker.js 38:15-46
 ```
As a workaround I added `request` as a dependency in my project and the error was fixed, but I think it should be listed in `dependencies` instead of `devDependencies` in this project. #27 was a similar issue and it was thankfully fixed a while ago. Or should it be added [here](https://github.com/googleapis/gax-nodejs/blob/main/package.json#L29)?

Update: I've opened [this](https://github.com/googleapis/gax-nodejs/issues/1149) issue

**Comment by kosukekurimoto** [comment]
この問題はまだ継続しています。
