### ISSUE TITLE
Problems with "duplicate" license file

### ISSUE THREAD

**Issue by basyskom-jvoe** [googleapis/retry-request#78]
#### Environment details

  - OS: Ubuntu 18.04 / Windows
  - Node.js version: v16.16.0
  - npm version: 8.11.0
  - `retry-request` version: 5.0.1

#### Description
The repository as well as the npm package contain two files named `LICENSE` and `license` which is a problem for environments that are not case sensitive.
For example, doing a zip deployment to an Azure function app running on Windows fails if retry-request is present in the node_modules directory (in my case, retry-request was introduced as a dependency of firebase-admin).
While one of the files could be excluded from the zip deployment via `.funcignore` once the issue was identified, it would be better not to have two files with names only differing in case in the first place.

**Comment by ddelgrosso1** [comment]
Looks like this was fixed: https://github.com/googleapis/retry-request/pull/82. Closing.
